/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code;

import code.database.Database;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebView;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.*;

/**
 *
 * @author user
 */
public class books extends javax.swing.JFrame {

    /**
     * Creates new form books
     */
    public books() {
        initComponents();
        pnlBooks.setLayout(new BoxLayout(pnlBooks, BoxLayout.Y_AXIS));
        loadBookCards();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBooks = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pnlBooks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlBooksLayout = new javax.swing.GroupLayout(pnlBooks);
        pnlBooks.setLayout(pnlBooksLayout);
        pnlBooksLayout.setHorizontalGroup(
            pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        pnlBooksLayout.setVerticalGroup(
            pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Nuestros libros");

        btnBack.setText("Regresar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(btnBack))
                    .addComponent(pnlBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            new view().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(books.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new books().setVisible(true);
            }
        });
    }

    private void loadBookCards() {
        // Limpiar el contenedor de libros
        pnlBooks.removeAll();
        pnlBooks.revalidate();
        pnlBooks.repaint();

        Database db = new Database();
        ResultSet rs = db.executeQuery(
                "SELECT b.title, b.author, b.publisher, b.price, b.image "
                + "FROM Book b",
                new String[0]
        );

        // Crear el contenedor único fuera del ciclo
        StringBuilder htmlContentBuilder = new StringBuilder();
        htmlContentBuilder.append("<html>")
                .append("<head>")
                .append("<style>")
                .append("* { font-family: Arial; }")
                .append(".card { border: 1px solid #ddd; border-radius: 10px; box-shadow: 0 0 1rem rgba(0, 0, 0, 0.2); padding: 20px; margin-bottom: 0.3rem; text-align: center; width: 300px; }")
                .append(".container { margin: auto; width: 100%; min-height: 100vh; display: grid; grid-template-columns: repeat(2, 1fr); align-items: center; grid-gap: 1rem; justify-items: center; box-shadow: 0 0 1rem rgba(0, 0, 0, 0.2); }")
                .append(".card img { max-width: 100%; border-radius: 10px; }")
                .append(".card h3 { margin: 10px 0; color: #333; }")
                .append(".card p { margin: 5px 0; color: #666; }")
                .append(".card .price { font-weight: bold; color: #2196F3; }")
                .append("</style>")
                .append("</head>")
                .append("<body>")
                .append("<div class='container'>");

        try {
            while (rs != null && rs.next()) {
                // Obtener los datos del libro
                String title = rs.getString("title");
                String author = rs.getString("author");
                String publisher = rs.getString("publisher");
                double price = rs.getDouble("price");
                // Obtener la ruta de la imagen desde la base de datos
                String imagePath = rs.getString("image");

                // Ruta de la imagen predeterminada
                String defaultImagePath = getClass().getResource("/Images/no-image.jpg").toExternalForm();

                // Asegúrate de usar la ruta relativa desde /Images/
                htmlContentBuilder.append("<div class='card'>")
                        .append("<img src='").append(imagePath != null ? "/Images/" + imagePath : defaultImagePath).append("' alt='Book Image' onerror='this.src=\"").append(defaultImagePath).append("\"'>")
                        .append("<h3>").append(title).append("</h3>")
                        .append("<p>Autor: ").append(author).append("</p>")
                        .append("<p>Editorial: ").append(publisher).append("</p>")
                        .append("<p class='price'>$").append(String.format("%.2f", price)).append("</p>")
                        .append("</div>");

            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar los libros: " + e.getMessage());
        }

        // Cerrar el contenedor
        htmlContentBuilder.append("</div>")
                .append("</body>")
                .append("</html>");

        // Crear el JFXPanel para mostrar las tarjetas
        JFXPanel fxPanel = new JFXPanel();

        // Crear la escena de JavaFX con el WebView
        Platform.runLater(() -> {
            WebView webView = new WebView();
            webView.getEngine().loadContent(htmlContentBuilder.toString());
            Scene scene = new Scene(webView);
            fxPanel.setScene(scene);
        });

        // Añadir el JFXPanel al panel de Swing
        pnlBooks.add(fxPanel);

        // Actualizar el contenedor
        pnlBooks.revalidate();
        pnlBooks.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBooks;
    // End of variables declaration//GEN-END:variables
}
